apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-weather
  labels:
    app: currency-weather
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-weather
  template:
    metadata:
      labels:
        app: currency-weather
    spec:
      containers:
        - name: currency-weather
          image: 500318249166.dkr.ecr.us-east-1.amazonaws.com/currency-weather:app1
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: currency-weather-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: currency-weather
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 3000 #The port for the React.js application container