apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-app
  labels:
    app: frontend-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-web-app
  template:
    metadata:
      labels:
        app: frontend-web-app
    spec:
      containers:
        - name: frontend-web-app
          image: 500318249166.dkr.ecr.ap-south-1.amazonaws.com/frontend/web-app
          ports:
            - containerPort: 80
